version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: apriori
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./api/database/postgres/postgres-data:/var/lib/postgresql/data
    networks:
      - thesis
    restart: always
  cache:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - thesis
  api:
    build: ./api
    ports:
      - "8080:8080"
    env_file:
      - ./api/.env.production
    depends_on:
      - db
    networks:
      - thesis
    restart: always
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./api/cmd/library/grafana/grafana-data:/var/lib/grafana
      - ./api/cmd/library/grafana/grafana-data:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=Rahasia123
    depends_on:
      - prometheus
    networks:
      - thesis
  prometheus:
    image: prom/prometheus:v2.27.1
    volumes:
      - ./api/cmd/library/prometheus:/etc/prometheus/
      - ./api/cmd/library/prometheus/prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    restart: always
    networks:
      - thesis
  nsqlookupd:
    image: nsqio/nsq
    ports:
      - "4160:4160"
      - "4161:4161"
    command: /nsqlookupd
    networks:
      - thesis
  nsqd:
    image: nsqio/nsq
    ports:
      - "4150:4150"
      - "4151:4151"
    depends_on:
      - nsqlookupd
    command: /nsqd -lookupd-tcp-address=nsqlookupd:4160 -broadcast-address=nsqd
    networks:
      - thesis
  nsqadmin:
    image: nsqio/nsq
    ports:
      - "4171:4171"
    depends_on:
      - nsqlookupd
      - nsqd
    command: /nsqadmin -lookupd-http-address=nsqlookupd:4161
    networks:
      - thesis
  messagebroker:
    build: ./message
    env_file:
      - ./message/.env
    ports:
      - "8082:8080"
    restart: always
    depends_on:
      - nsqlookupd
    networks:
      - thesis

networks:
  thesis:
    driver: bridge