version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: apriori
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./api/database/migration/postgres/database:/var/lib/postgresql/data
    networks:
      - thesis
    restart: always
  cache:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - thesis
  migrate:
    image: migrate/migrate
    volumes:
      - ./api/database/migration/postgres:/migrations
    command: ["-path", "/migrations", "-database", "postgres://root:root@apriori-db-1:5432/apriori?sslmode=disable", "-verbose", "up"]
    depends_on:
      - db
    networks:
      - thesis

networks:
  thesis:
    driver: bridge