// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/99designs/gqlgen/graphql"
)

type AddReceiptNumberRequest struct {
	OrderId       string `json:"order_id"`
	ReceiptNumber string `json:"receipt_number"`
}

type Apriori struct {
	IdApriori   int        `json:"id_apriori"`
	Code        string     `json:"code"`
	Item        string     `json:"item"`
	Discount    float64    `json:"discount"`
	Support     float64    `json:"support"`
	Confidence  float64    `json:"confidence"`
	RangeDate   string     `json:"range_date"`
	IsActive    bool       `json:"is_active"`
	Description *string    `json:"description"`
	Mass        int        `json:"mass"`
	Image       *string    `json:"image"`
	CreatedAt   time.Time  `json:"created_at"`
	UserOrder   *UserOrder `json:"user_order"`
}

type Category struct {
	IdCategory int       `json:"id_category"`
	Name       string    `json:"name"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Comment struct {
	IdComment   int        `json:"id_comment"`
	UserOrderId int        `json:"user_order_id"`
	ProductCode string     `json:"product_code"`
	Description *string    `json:"description"`
	Tag         *string    `json:"tag"`
	Rating      int        `json:"rating"`
	CreatedAt   time.Time  `json:"created_at"`
	UserOrder   *UserOrder `json:"user_order"`
}

type CreateAprioriRequest struct {
	Item       string  `json:"item"`
	Discount   float64 `json:"discount"`
	Support    float64 `json:"support"`
	Confidence float64 `json:"confidence"`
	RangeDate  string  `json:"range_date"`
	CreatedAt  string  `json:"created_at"`
}

type CreateCategoryRequest struct {
	Name string `json:"name"`
}

type CreateCommentRequest struct {
	UserOrderId int    `json:"user_order_id"`
	ProductCode string `json:"product_code"`
	Description string `json:"description"`
	Tag         string `json:"tag"`
	Rating      int    `json:"rating"`
}

type CreateNotificationRequest struct {
	UserId      int    `json:"user_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	URL         string `json:"url"`
	IsRead      bool   `json:"is_read"`
	CreatedAt   string `json:"created_at"`
}

type CreatePasswordResetRequest struct {
	Email string `json:"email"`
}

type CreateProductRequest struct {
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Price       int            `json:"price"`
	Category    string         `json:"category"`
	Mass        int            `json:"mass"`
	Image       graphql.Upload `json:"image"`
}

type CreateTransactionFromFileRequest struct {
	File int64 `json:"file"`
}

type CreateTransactionRequest struct {
	ProductName  string `json:"product_name"`
	CustomerName string `json:"customer_name"`
}

type CreateUserRequest struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Address  string `json:"address"`
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type GenerateApriori struct {
	ItemSet     []string `json:"item_set"`
	Support     float64  `json:"support"`
	Iterate     int      `json:"iterate"`
	Transaction int      `json:"transaction"`
	Confidence  float64  `json:"confidence"`
	Discount    float64  `json:"discount"`
	Description string   `json:"description"`
	RangeDate   string   `json:"range_date"`
}

type GenerateAprioriRequest struct {
	MinimumSupport    float64 `json:"minimum_support"`
	MinimumConfidence float64 `json:"minimum_confidence"`
	MinimumDiscount   int     `json:"minimum_discount"`
	MaximumDiscount   int     `json:"maximum_discount"`
	StartDate         string  `json:"start_date"`
	EndDate           string  `json:"end_date"`
}

type GenerateCreateAprioriRequest struct {
	ItemSet     []string `json:"item_set"`
	Support     float64  `json:"support"`
	Iterate     int      `json:"iterate"`
	Transaction int      `json:"transaction"`
	Confidence  float64  `json:"confidence"`
	Discount    float64  `json:"discount"`
	Description string   `json:"description"`
	RangeDate   string   `json:"range_date"`
}

type GetDeliveryRequest struct {
	Origin      string `json:"origin"`
	Destination string `json:"destination"`
	Weight      int    `json:"weight"`
	Courier     string `json:"courier"`
}

type GetPaymentTokenRequest struct {
	GrossAmount    int64    `json:"gross_amount"`
	Items          []string `json:"items"`
	UserId         int      `json:"user_id"`
	CustomerName   string   `json:"customer_name"`
	Address        string   `json:"address"`
	Courier        string   `json:"courier"`
	CourierService string   `json:"courier_service"`
	ShippingCost   int64    `json:"shipping_cost"`
}

type GetProductNameTransactionResponse struct {
	ProductName []string `json:"product_name"`
}

type GetRefreshTokenRequest struct {
	RefreshToken string `json:"refresh_token"`
}

type GetUserCredentialRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Notification struct {
	IdNotification int       `json:"id_notification"`
	UserId         int       `json:"user_id"`
	Title          string    `json:"title"`
	Description    *string   `json:"description"`
	URL            *string   `json:"url"`
	IsRead         bool      `json:"is_read"`
	CreatedAt      time.Time `json:"created_at"`
	User           *User     `json:"user"`
}

type PasswordReset struct {
	Email   string `json:"email"`
	Token   string `json:"token"`
	Expired int64  `json:"expired"`
}

type Payment struct {
	IdPayload         int          `json:"id_payload"`
	UserId            int          `json:"user_id"`
	OrderId           *string      `json:"order_id"`
	TransactionTime   *string      `json:"transaction_time"`
	TransactionStatus *string      `json:"transaction_status"`
	TransactionId     *string      `json:"transaction_id"`
	StatusCode        *string      `json:"status_code"`
	SignatureKey      *string      `json:"signature_key"`
	SettlementTime    *string      `json:"settlement_time"`
	PaymentType       *string      `json:"payment_type"`
	MerchantId        *string      `json:"merchant_id"`
	GrossAmount       *string      `json:"gross_amount"`
	FraudStatus       *string      `json:"fraud_status"`
	BankType          *string      `json:"bank_type"`
	VANumber          *string      `json:"va_number"`
	BillerCode        *string      `json:"biller_code"`
	BillKey           *string      `json:"bill_key"`
	ReceiptNumber     *string      `json:"receipt_number"`
	Address           *string      `json:"address"`
	Courier           *string      `json:"courier"`
	CourierService    *string      `json:"courier_service"`
	User              *User        `json:"user"`
	UserOrder         []*UserOrder `json:"user_order"`
}

type Product struct {
	IdProduct   int       `json:"id_product"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Price       int       `json:"price"`
	Category    string    `json:"category"`
	IsEmpty     bool      `json:"is_empty"`
	Mass        int       `json:"mass"`
	Image       *string   `json:"image"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ProductRecommendation struct {
	AprioriId          int     `json:"apriori_id"`
	AprioriCode        string  `json:"apriori_code"`
	AprioriItem        string  `json:"apriori_item"`
	AprioriDiscount    float64 `json:"apriori_discount"`
	AprioriDescription *string `json:"apriori_description"`
	AprioriImage       *string `json:"apriori_image"`
	ProductTotalPrice  int     `json:"product_total_price"`
	PriceDiscount      int     `json:"price_discount"`
	Mass               int     `json:"mass"`
}

type RatingFromComment struct {
	Rating        int `json:"rating"`
	ResultRating  int `json:"result_rating"`
	ResultComment int `json:"result_comment"`
}

type TokenJwt struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type Transaction struct {
	IdTransaction int       `json:"id_transaction"`
	ProductName   string    `json:"product_name"`
	CustomerName  string    `json:"customer_name"`
	NoTransaction string    `json:"no_transaction"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type UpdateAprioriRequest struct {
	IdApriori   int            `json:"id_apriori"`
	Code        string         `json:"code"`
	Description string         `json:"description"`
	Image       graphql.Upload `json:"image"`
}

type UpdateCategoryRequest struct {
	IdCategory int    `json:"id_category"`
	Name       string `json:"name"`
}

type UpdateProductRequest struct {
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Price       int            `json:"price"`
	Category    string         `json:"category"`
	IsEmpty     bool           `json:"is_empty"`
	Mass        int            `json:"mass"`
	Image       graphql.Upload `json:"image"`
}

type UpdateResetPasswordUserRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Token    string `json:"token"`
}

type UpdateTransactionRequest struct {
	ProductName   string `json:"product_name"`
	CustomerName  string `json:"customer_name"`
	NoTransaction string `json:"no_transaction"`
}

type UpdateUserRequest struct {
	IdUser   *int   `json:"id_user"`
	Role     int    `json:"role"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Address  string `json:"address"`
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type User struct {
	IdUser       int             `json:"id_user"`
	Role         int             `json:"role"`
	Name         string          `json:"name"`
	Email        string          `json:"email"`
	Address      string          `json:"address"`
	Phone        string          `json:"phone"`
	Password     string          `json:"password"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
	Notification []*Notification `json:"notification"`
	Payment      []*Payment      `json:"payment"`
}

type UserOrder struct {
	IdOrder        int      `json:"id_order"`
	PayloadId      int      `json:"payload_id"`
	Code           *string  `json:"code"`
	Name           *string  `json:"name"`
	Price          *int64   `json:"price"`
	Image          *string  `json:"image"`
	Quantity       *int     `json:"quantity"`
	TotalPriceItem *int64   `json:"total_price_item"`
	Payment        *Payment `json:"payment"`
}
