// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Apriori struct {
	IDApriori   string     `json:"id_apriori"`
	Code        string     `json:"code"`
	Item        string     `json:"item"`
	Discount    float64    `json:"discount"`
	Support     float64    `json:"support"`
	Confidence  float64    `json:"confidence"`
	RangeDate   string     `json:"range_date"`
	IsActive    bool       `json:"is_active"`
	Description *string    `json:"description"`
	Mass        int        `json:"mass"`
	Image       *string    `json:"image"`
	CreatedAt   string     `json:"created_at"`
	UserOrder   *UserOrder `json:"user_order"`
}

type Category struct {
	IDCategory string `json:"id_category"`
	Name       string `json:"name"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type Comment struct {
	IDComment   string     `json:"id_comment"`
	UserOrderID string     `json:"user_order_id"`
	ProductCode string     `json:"product_code"`
	Description *string    `json:"description"`
	Tag         *string    `json:"tag"`
	Rating      int        `json:"rating"`
	CreatedAt   string     `json:"created_at"`
	UserOrder   *UserOrder `json:"user_order"`
}

type GenerateApriori struct {
	ItemSet     []string `json:"item_set"`
	Support     float64  `json:"support"`
	Iterate     int      `json:"iterate"`
	Transaction int      `json:"transaction"`
	Confidence  float64  `json:"confidence"`
	Discount    float64  `json:"discount"`
	Description string   `json:"description"`
	RangeDate   string   `json:"range_date"`
}

type NewProduct struct {
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Price       int     `json:"price"`
	Category    string  `json:"category"`
	Mass        int     `json:"mass"`
	Image       *string `json:"image"`
}

type Notification struct {
	IDNotification string  `json:"id_notification"`
	UserID         string  `json:"user_id"`
	Title          string  `json:"title"`
	Description    *string `json:"description"`
	URL            *string `json:"url"`
	IsRead         bool    `json:"is_read"`
	CreatedAt      string  `json:"created_at"`
	User           *User   `json:"user"`
}

type PasswordReset struct {
	Email   string `json:"email"`
	Token   string `json:"token"`
	Expired int    `json:"expired"`
}

type Payment struct {
	IDPayload         string       `json:"id_payload"`
	UserID            string       `json:"user_id"`
	OrderID           *string      `json:"order_id"`
	TransactionTime   *string      `json:"transaction_time"`
	TransactionStatus *string      `json:"transaction_status"`
	TransactionID     *string      `json:"transaction_id"`
	StatusCode        *string      `json:"status_code"`
	SignatureKey      *string      `json:"signature_key"`
	SettlementTime    *string      `json:"settlement_time"`
	PaymentType       *string      `json:"payment_type"`
	MerchantID        *string      `json:"merchant_id"`
	GrossAmount       *string      `json:"gross_amount"`
	FraudStatus       *string      `json:"fraud_status"`
	BankType          *string      `json:"bank_type"`
	VaNumber          *string      `json:"va_number"`
	BillerCode        *string      `json:"biller_code"`
	BillKey           *string      `json:"bill_key"`
	ReceiptNumber     *string      `json:"receipt_number"`
	Address           *string      `json:"address"`
	Courier           *string      `json:"courier"`
	CourierService    *string      `json:"courier_service"`
	User              *User        `json:"user"`
	UserOrder         []*UserOrder `json:"user_order"`
}

type Product struct {
	IDProduct   string  `json:"id_product"`
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Price       int     `json:"price"`
	Category    string  `json:"category"`
	IsEmpty     bool    `json:"is_empty"`
	Mass        int     `json:"mass"`
	Image       *string `json:"image"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
}

type ProductRecommendation struct {
	AprioriID          string  `json:"apriori_id"`
	AprioriCode        string  `json:"apriori_code"`
	AprioriItem        string  `json:"apriori_item"`
	AprioriDiscount    float64 `json:"apriori_discount"`
	ProductTotalPrice  int     `json:"product_total_price"`
	PriceDiscount      int     `json:"price_discount"`
	AprioriImage       *string `json:"apriori_image"`
	Mass               int     `json:"mass"`
	AprioriDescription *string `json:"apriori_description"`
}

type RatingFromComment struct {
	Rating        int `json:"rating"`
	ResultRating  int `json:"result_rating"`
	ResultComment int `json:"result_comment"`
}

type Transaction struct {
	IDTransaction string `json:"id_transaction"`
	ProductName   string `json:"product_name"`
	CustomerName  string `json:"customer_name"`
	NoTransaction string `json:"no_transaction"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

type User struct {
	IDUser       string          `json:"id_user"`
	Role         int             `json:"role"`
	Name         string          `json:"name"`
	Email        string          `json:"email"`
	Address      string          `json:"address"`
	Phone        string          `json:"phone"`
	Password     string          `json:"password"`
	CreatedAt    string          `json:"created_at"`
	UpdatedAt    string          `json:"updated_at"`
	Notification []*Notification `json:"notification"`
	Payment      []*Payment      `json:"payment"`
}

type UserOrder struct {
	IDOrder        string   `json:"id_order"`
	PayloadID      string   `json:"payload_id"`
	Code           *string  `json:"code"`
	Name           *string  `json:"name"`
	Price          *int     `json:"price"`
	Image          *string  `json:"image"`
	Quantity       *int     `json:"quantity"`
	TotalPriceItem *int     `json:"total_price_item"`
	Payment        *Payment `json:"payment"`
}
