scalar Time
scalar Int64
scalar Upload
scalar Map
scalar Any

directive @goField(
    forceResolver: Boolean
    name: String
) on INPUT_FIELD_DEFINITION | FIELD_DEFINITION

directive @binding(
    constraint: String!
) on INPUT_FIELD_DEFINITION | ARGUMENT_DEFINITION

directive @hasRole(
    roles: String!
    useApiKey: Boolean
) on FIELD_DEFINITION

directive @apiKey on FIELD_DEFINITION