type Transaction {
    id_transaction: ID! @goField(name: "IdTransaction")
    product_name: String!
    customer_name: String!
    no_transaction: String!
    created_at: Time!
    updated_at: Time!
}

type GetProductNameTransactionResponse {
    product_name: [String!]!
}

input CreateTransactionRequest {
    product_name: String! @binding(constraint: "required,max=256")
    customer_name: String! @binding(constraint: "required,max=100")
}

input CreateTransactionFromFileRequest {
    file: Int64! @binding(constraint: "required")
}

input UpdateTransactionRequest {
    product_name: String! @binding(constraint: "required,max=256")
    customer_name: String! @binding(constraint: "required,max=100")
    no_transaction: String!
}
