type Apriori {
    id_apriori: ID! @goField(name: "IdApriori")
    code: String!
    item: String!
    discount: Float!
    support: Float!
    confidence: Float!
    range_date: String!
    is_active: Boolean!
    description: String
    mass: Int!
    image: String
    created_at: Time!
    user_order: UserOrder!
}

type GenerateApriori {
    item_set : [String!]!
    support: Float!
    iterate: Int!
    transaction: Int!
    confidence: Float!
    discount: Float!
    description: String!
    range_date: String!
}

input GenerateCreateAprioriRequest {
    item_set : [String!]!
    support: Float!
    iterate: Int!
    transaction: Int!
    confidence: Float!
    discount: Float!
    description: String!
    range_date: String!
}

input CreateAprioriRequest {
    item: String!
    discount: Float!
    support: Float!
    confidence: Float!
    range_date: String!
    created_at: String!
}

input UpdateAprioriRequest {
    id_apriori: ID! @goField(name: "IdApriori")
    code: String!
    description: String!
    image: String!
}

input GenerateAprioriRequest {
    minimum_support: Float! @binding(constraint: "required,max=100")
    minimum_confidence: Float! @binding(constraint: "required,max=100")
    minimum_discount: Int! @binding(constraint: "required")
    maximum_discount: Int! @binding(constraint: "required,gtefield=MinimumDiscount")
    start_date: String! @binding(constraint: "required")
    end_date: String! @binding(constraint: "required")
}