type Comment {
    id_comment: ID! @goField(name: "IdComment")
    user_order_id: ID! @goField(name: "UserOrderId")
    product_code: String!
    description: String
    tag: String
    rating: Int!
    created_at: Time!
    user_order: UserOrder
}

type RatingFromComment {
    rating: Int!
    result_rating: Int!
    result_comment: Int!
}

input CreateCommentRequest {
    user_order_id: ID! @goField(name: "UserOrderId")
    product_code: String!
    description: String!
    tag: String!
    rating: Int! @binding(constraint: "required")
    created_at: String!
}