type Notification {
    id_notification: ID! @goField(name: "IdNotification")
    user_id: ID! @goField(name: "UserId")
    title: String!
    description: String
    url: String
    is_read: Boolean!
    created_at: Time!
    user: User!
}