type PasswordReset {
    email: String!
    token: String!
    expired: Int64!
}

input CreatePasswordResetRequest {
    email: String! @binding(constraint: "required,email")
}

input UpdateResetPasswordUserRequest {
    email: String! @binding(constraint: "required,email")
    password: String! @binding(constraint: "required,min=6")
    token: String!
}