type Query {
  #   Auth
  AuthToken: Boolean! @apiKey

  #   User
  UserFindAll: [User!]! @hasRole(roles: "admin")
  UserProfile: User! @hasRole(roles: "user")
  UserFindById(id: ID!): User! @hasRole(roles: "admin")

  #   Category
  CategoryFindAll: [Category!]! @apiKey
  CategoryFindById(id: ID!): Category! @hasRole(roles: "user")

  #   Transaction
  TransactionFindAll: [Transaction!]! @hasRole(roles: "admin")
  TransactionFindByNoTransaction(number_transaction: String!): Transaction! @hasRole(roles: "admin")

  #   Payment
  PaymentFindAll: [Payment!]! @hasRole(roles: "admin")
  PaymentFindByOrderId(order_id: String!): Payment! @hasRole(roles: "admin")

  #   User Order
  UserOrderFindAll: [Payment!]! @hasRole(roles: "user")
  UserOrderFindAllByUserId: [UserOrder!]! @hasRole(roles: "user")
  UserOrderFindAllById(order_id: String!): [UserOrder!]! @hasRole(roles: "user")
  UserOrderFindById(id: ID!): UserOrder! @hasRole(roles: "user")

  #   Comment
  CommentFindAllRatingByProductCode(product_code: String!): [RatingFromComment!]! @apiKey
  CommentFindAllByProductCode(product_id: String!, tags: String!, ratings: String!): [Comment!]! @apiKey
  CommentFindByUserOrderId(user_order_id: ID!): Comment! @apiKey
  CommentFindById(id: ID!): Comment! @apiKey

  #   Raja Ongkir
  RajaOngkirFindAll(place: String!, province: String): Any! @apiKey

  #   Notification
  NotificationFindAll: [Notification!]! @hasRole(roles: "admin")
  NotificationFindAllByUserId: [Notification!]! @hasRole(roles: "user")

  #   Apriori
  AprioriFindAll: [Apriori!]! @apiKey
  AprioriFindAllByCode(code: String!): [Apriori!]! @apiKey
  AprioriFindAllByActive: [Apriori!]! @apiKey
  AprioriFindByCodeAndId(code: String!, id: ID!): ProductRecommendation! @apiKey

  #   Product
  ProductFindAllByAdmin: [Product!]! @hasRole(roles: "admin")
  ProductFindAllSimilarCategory(code: String!): [Product!]! @apiKey
  ProductFindAllByUser(search: String, category: String): [Product!]! @apiKey
  ProductFindAllRecommendation(code: String!): [ProductRecommendation!]! @apiKey
  ProductFindByCode(code: String!): Product! @apiKey
}