type User {
    id_user: ID! @goField(name: "IdUser")
    role: Int!
    name: String!
    email: String!
    address: String!
    phone: String!
    password: String!
    created_at: Time!
    updated_at: Time!
    notification: [Notification!]!
    payment: [Payment!]!
}